siteweb/urls.py
from django.urls import path

from siteweb import views
from django.conf.urls.static import static
from django.conf import settings

# Gestion du routing décidant quelle fonction va traiter telle requête HTTP.

# Règles de matching intégré dans la variable urlpatterns
urlpatterns = [
    path('', views.accueil, name='index'),
    path('accueil/', views.accueil, name='accueil'),
    path('chronologie/', views.chronologie, name='chronologie'),
    path('cnn/', views.cnn, name='cnn'),
    path('rnn/', views.rnn, name='rnn'),
    path('image/', views.image, name='image'),
    path('image/predictImage', views.predictImage, name='predictImage'),
    path('texte/', views.texte, name='texte'),
    path('video/', views.video, name='video'),
    path('audio/', views.audio, name='audio'),

    # URLs de gestion du Blog
    path('posts/', views.post_list, name='home'),
    path('posts/<str:category_name>/', views.post_list, name='post-list'),
    path('posts/detail/<int:post_id>/', views.post_detail, name='post-detail'),

    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
]
# Ajout de l'emplacement du dossier MEDIA, un dossier où seront enregistrés des images envoyées par l'utilisateur
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitewebdnn/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('site/', include('siteweb.urls')),
    path('', include('siteweb.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

siteweb/models.py
from django.db import models
from django.template.defaultfilters import slugify
from ckeditor_uploader.fields import RichTextUploadingField

# Ce fichier gère la création de modèles de données via une classe de représentation des données que l'on souhaite
# manipuler et stocker dans une base de données. Une classe assure ainsi l'ajout et la synchronisation
# des tables de base données.

# Un modèle = une classe = une table
# chaque attribut d'une classe représente une colonne d'une table

class PostCategory(models.Model):
    # La classe Postcategory héritant de models.Model
    name = models.CharField(max_length=50)
    # PostCategory est uniquement défini par un nom

    # slugify() transforme une catégorie en URL valide en remplaçant les espaces par un tiret
    # ainsi que les majuscules en minuscules
    def slug(self):
        return slugify(self.name)

    def __str__(self):
        # Surcharge de la méthode __str__
        return self.name
        # retourne le nom de la catégorie

class Post(models.Model):
    # La classe Posts héritant de models.Model
    title = models.CharField(max_length=100)
    category = models.ForeignKey('PostCategory',
    # Une clé étrangère vers PostCategory, suivi de la configuration possible :
                                 null=True,
                                 # Autorise le fait d'avoir une valeur nulle
                                 blank=True,
                                 # Autorise le fait d'avoir une chaîne vide
                                 on_delete=models.DO_NOTHING)
                                 # Lors de la suppression ne rien faire

    published = models.BooleanField(default=False)
    # le statu publié ou non du post, sachant que par défaut un post n'est pas publié (default = False)
    text = RichTextUploadingField()
    #  La mise en forme de la partie message du post est enrichie à l'aide du package ckeditor
    created_at = models.DateTimeField(auto_now_add=True)
    # Enregistrement de la date de création du post

    def __str__(self):
        return self.title
        # Retourne le titre

siteweb/forms.py
from django import forms


# un pattern Django form simplifie la génération et le traitement des formulaires HTML

# Chaque attribut correspond à un input attendu dans un formulaire et dont le type déterminera le rendu
# Une foi que la classe est définir il suffit d'injecter une instance de ce form dans un template
# et Django se changera du rendu, de la vérification d'erreurs côté client et de la vérification d'erreurs côté serveur
# au moment de la récupération des informations et du traitement du formulaire.

class ContactForm(forms.Form):
    # Une classe héritant de forms.Form
    from_email = forms.EmailField(required=True)
    # L'attribut email
    subject = forms.CharField(required=True)
    # L'attribut sujet du formulaire
    message = forms.CharField(widget=forms.Textarea, required=True)
    # L'attribut dédié au message

siteweb/views.py
from django.shortcuts import get_object_or_404
from siteweb.models import Post
from siteweb import model_helpers
from siteweb import navigation
from django.core.files.storage import FileSystemStorage
from django.core.mail import send_mail, BadHeaderError
from django.shortcuts import render
from .forms import ContactForm
from django.conf import settings
from django.contrib import messages

import requests
import urllib
import json

# Le fichier views.py contient les fonctions générant les réponses HTTP à renvoyer au navigateur de l'utilisateur
# La liste des fonctions qui seront appelées par le module de routing (définit dans le fichier urls.py)

def accueil(request):
    # La fonction associée à la rubrique accueil de la barre de navigation
    context = {
        'navigation_items': navigation.navigation_items(navigation.NAV_ACCUEIL),
    }

    return render(request, 'site/accueil.html', context)
    # Retourne le contexte et l'emplacement du fichier accueil.html


def chronologie(request):
    # La fonction associée à la rubrique chronologie de la barre de navigation
    context = {
        'navigation_items': navigation.navigation_items(navigation.NAV_CHRONOLOGIE),
    }

    return render(request, 'site/chronologie.html', context)
    # Retourne le contexte et l'emplacement du fichier chronologie.html

def cnn(request):
    # La fonction associée à la rubrique cnn de la barre de navigation
    context = {
        'navigation_items': navigation.navigation_items(navigation.NAV_CNN),
    }

    return render(request, 'site/cnn.html', context)
    # retourne le contexte et l'emplacement du fichier cnn.html

def rnn(request):
    # La fonction associée à la rubrique rnn de la barre de navigation
    context = {
        'navigation_items': navigation.navigation_items(navigation.NAV_RNN),
    }

    return render(request, 'site/rnn.html', context)
    # Retourne le contexte et l'emplacement du fichier rnn.html


def post_list(request, category_name=model_helpers.post_category_all.slug()):
    # La fonction associée à la rubrique blog de la barre de navigation et dédiée à l'affichage de l'ensemble des posts
    category, posts = model_helpers.get_category_and_posts(category_name)
    # récupère la catégorie et les posts à afficher suivant leur sélection par l'utilisateur
    categories = model_helpers.get_categories()
    # Récupère les catégories à afficher sur la partie droite du blog

    context = {
        'navigation_items': navigation.navigation_items(navigation.NAV_POSTS),
        # L'objet Blog de la barre de navigation
        'category': category,
        # La catégorie
        'posts': posts,
        # Le ou les pots
        'categories': categories,
        # L'ensemble des catégories à afficher pour sélection
    }

    return render(request, 'site/post_list.html', context)
    # Retourne le contexte et l'emplacement du fichier post_list.html

def post_detail(request, post_id):
    # La fonction associée à la rubrique blog de la barre de navigation et dédiée à l'affichage d'un seul post
    post = get_object_or_404(Post, pk=post_id)
    # Récupérer le post ou une erreur à partir de son identifiant dans la table de base de données Post
    posts_same_category = Post.objects.filter(published=True, category=post.category) \
        .exclude(pk=post_id)
    # Récupérer les posts publiés d'une même catégorie

    context = {
        'navigation_items': navigation.navigation_items(navigation.NAV_POSTS),
        # L'objet Blog de la barre de navigation
        'post': post,
        # Le post
        'posts_same_category': posts_same_category,
        # Les posts de même catégories

    }

    return render(request, 'site/post_detail.html', context)
    # Retourne le contexte et l'emplacement du fichier post_detail.html


def image(request):
    # La fonction associée à la rubrique Application Image de la barre de navigation
    context = {
        'navigation_items': navigation.navigation_items(navigation.NAV_IMAGE),
        # L'objet Image de la barre de navigation
    }

    return render(request, 'site/application_image.html', context)
    # Retourne le contexte et l'emplacement du fichier application_image.html


def predictImage(request):
    # La fonction associée à la rubrique Application Image de la barre de navigation assurant la prédiction d'une image
    fileobj = request.FILES['filePath']
    # Recupérer l'emplacement de l'image
    #print("fileobj")
    #print(fileobj)
    fs = FileSystemStorage()
    filePathName = fs.save(fileobj.name, fileobj)
    # Enregistrer l'image dans le dossier media du serveur web
    filePathName = fs.url(filePathName)
    testimage = '.' + filePathName
    #print("testimage")
    #print(testimage)
    api = settings.URL_TUMOR_API
    upload = {
        'picture': open(testimage, 'rb')
    }
    response = requests.post(api, files=upload)
    # Envoyer l'image à l'API
    data = response.json()
    # Réponse de l'API proposant les résultats de la prédiction


    context = {
        'vgg_prediction': data['vgg_tumor_pred'],
        # Le résultat de la prédiction du modèle VGG
        'resnet_prediction': data['resnet_tumor_pred'],
        # Le résultat de la prédiction du modèle resnet
        'inception_resnet_v2_prediction': data['inception_resnet_v2_tumor_pred'],
        # Le résultat de la prédiction du modèle inception resnet V2
        'navigation_items': navigation.navigation_items(navigation.NAV_IMAGE),
        # L'objet Image de la barre de navigation
    }
    return render(request, 'site/application_image.html', context)
    # Retourne le contexte et l'emplacement du fichier application_image.html


def texte(request):
    # La fonction associée à la rubrique Application Texte de la barre de navigation
    context = {
        'navigation_items': navigation.navigation_items(navigation.NAV_TEXTE),
    }
    # L'objet Texte de la barre de navigation

    return render(request, 'site/application_texte.html', context)
    # retourne le contexte et l'emplacement du fichier application_texte.html

def video(request):
    # La fonction associée à la rubrique Application Vidéo de la barre de navigation
    context = {
        'navigation_items': navigation.navigation_items(navigation.NAV_VIDEO),
    }
    # L'objet Vidéo de la barre de navigation

    return render(request, 'site/application_video.html', context)
    # Retourne le contexte et l'emplacement du fichier application_video.html


def audio(request):
    # La fonction associée à la rubrique Application Audio de la barre de navigation
    context = {
        'navigation_items': navigation.navigation_items(navigation.NAV_AUDIO),
    }
    # L'objet audio de la barre de navigation

    return render(request, 'site/application_audio.html', context)
    # Retourne le contexte et l'emplacement du fichier application_audio.html


def about(request):
    # La fonction associée à la rubrique À Propos de la barre de navigation
    context = {
        'navigation_items': navigation.navigation_items(navigation.NAV_ABOUT),
    }
    # Lo'bjet about de la barre de navigation

    return render(request, 'site/about.html', context)
    # Retourne le contexte et l'emplacement du fichier about.html


def contact(request):
    # La fonction associée à la rubrique À Propos de la barre de navigation
    context = {
        'navigation_items': navigation.navigation_items(navigation.NAV_CONTACT),
        # L'objet Contact de la barre de navigation
    }
    if request.method == 'POST':
        # Si la méthode est de type POST
        form = ContactForm(request.POST)
        # récupérer l'objet form
        if form.is_valid():
            # si l'objet est valide
            from_email = form.cleaned_data['from_email']
            # Récupérer l'e-mail d'envoi
            subject = form.cleaned_data['subject']
            # Récupérer le sujet du mail
            message = form.cleaned_data['message']
            # Récupérer le message du mail
            message = "De : " + str(from_email) + " - " + str(message)
            # Ajouter l'adresse du mail de l'émetteur dans le mail reçu par l'administration
            ''' Begin reCAPTCHA validation '''
            recaptcha_response = request.POST.get('g-recaptcha-response')
            # Retour du recaptcha
            url = settings.URL_GOOGLE_API
            # Enregistrer dans la variable url, l'adresse de l'API Google du recaptcha
            values = {
                'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                # La clé secrète
                'response': recaptcha_response
                # la réponse
            }
            data = urllib.parse.urlencode(values).encode()
            # urllib.parse.urlencode convertir le dictionnaire value en chaîne de requête.
            req = urllib.request.Request(url, data=data)
            # Envoi de la requète à l'API Google
            response = urllib.request.urlopen(req)
            # retour de la réponse
            result = json.loads(response.read().decode())
            ''' End reCAPTCHA validation '''
            # Résultat de la réponse
            if result['success']:
                # le résultat est correct
                try:
                    send_mail(subject, message, from_email, ['patriceblanchard.perso@gmail.com'])
                    # Le sujet, le mail et le mail est envoyé à l'adresse mail 'patriceblanchard.perso@gmail.com'
                except BadHeaderError:
                    return render(request, "site/contact_error.html", context)
                    # en cas d'erreur, la page contact_error le signale
                return render(request, "site/contact_success.html", context)
                # en cas de réussite, la page contact_success spécifie que le mail a bien été envoyé
            else:
                messages.error(request, 'Invalid reCAPTCHA. Please try again.')
                # sinon le recaptcha présente un problème
                form = ContactForm()

siteweb/templates/site/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %} À propos {% endblock %}

{% block content %}
<div class="col-12">
    <br>
    <br>
    <h3>Patrice Blanchard</h3>
    <hr>
    <div class="row">
        <div class="col-md-9">
            <p>
                Étudiant à l'institut d'enseignement à distance de l'université Paris 8.
                <br>
                <br>
                Licence Informatique / Psychologie.
                <br>
                <br>
                La création de ce site web sous django et django REST API dédié au <span class="fst-italic">deep Learning</span> s'insère dans le cadre
                d'un projet de licence 2.
            </p>
            <br>
	    <p>
                Les dernières avancées technologiques en lien avec le <span class="fst-italic">deep learning</span> ont
                connu une évolution sans précédent ces dernières années. En effet, de nouvelles combinaisons et/ou
                optimisations d'architectures sont proposées lors de défis réunissant de nombreuses équipes de
                recherches, attendues par exemple lors la compétition ImageNet de Reconnaissance Visuelle à Grande
                Échelle organisée tous les ans.
	    <br>
	    <p>
	        De toute évidence, ce site web n'en est qu'à ses débuts, je prévois à
                l'avenir d'agrémenter son contenu d'explications plus détaillées ainsi que de projets de L3 au fil de
                mon apprentissage.
	    </p>
	    <br>
        </div>
        <div class="col-md-3">
            <img src="{% static 'img/a_propos/moi.jpg' %}" class="rounded mx-auto d-block" width="60%">
        </div>
    </div>
</div>

{% endblock content %}

siteweb/templates/site/accueil.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Accueil {% endblock %}

{% block content %}

<div class="col-12">
    <br>
    <br>
    <h4 class="text-center text-decoration-underline">
        Bienvenue
    </h4>
    <br>
    <br>
    <p class="text-start">
        Ce site web peut être perçu comme un point de départ pour apprendre les rudiments des réseaux de neurones
        profonds plus communément associés à l'appellation : <span class="fst-italic">deep learning</span>, en français
        «l'apprentissage profond». Je vais notamment présenté les deux paradigmes les plus populaires de ce
        domaine, ceux qui ont permis à la sphère du machine learning de réaliser un bond considérable durant les
        dernières décennies :
    </p>
    <br>
    <p class="text-center">
        Il s’agit du réseau de neurones convolutifs et du réseau de neurones récurrents.
    </p>
    <br>
    <p class="text-center fw-bold text-decoration-underline">
        Leurs domaines d'application :
    </p>
    <br>
    <p class="text-start">
        Un <label class="fw-bold">réseau de neurones à convolutions profondes</label>, de l’anglais DCNN pour
        <span class="fst-italic">Deep Convolutional Neural Network</span>, souvent raccourci en CNN, est un type de
        réseaux de neurones artificiels, principalement usité dans le cadre d'opérations mathématiques traduites en
        langage informatique impliquant des données de type spatial. C'est la raison pour laquelle ce type de réseau est
        idéalement conçu pour la classification d’images ou encore la détection d'objets, de personnes.
    </p>
    <p class="text-start">
        Un <label class="fw-bold">réseau de neurones récurrents</label>, alias RNN en anglais <span
            class="fst-italic">Recurrent Neural Network</span> est une autre classe de réseaux de neurones artificiels
        spécialisée dans le traitement de données temporelles ou séquentielles comme la traduction de langages,
        l’analyse du discours, des données financières, de la météo et bien plus encore.
    <p>
    <p class="text-center fw-bold text-decoration-underline">
        Définitions :
    </p>
    <p>
        Les différentes technologies citées auparavant font partie des nombreuses terminologies et méthodes de calcul
        utilisées dans le domaine de l’intelligence artificielle :

    </p>
    <br>
    <img src="{% static 'img/accueil/infographie.svg' %}" class=" w-50 rounded mx-auto d-block">
    <br>
    <p class="text-center text-decoration-underline">
        Arrêtons-nous quelques instants sur cette infographie pour ainsi comprendre plus précisément chaque élément de
        sa composition :
    </p>
    <br>
    <p class="text-center fw-bold text-decoration-underline">
        L’intelligence artificielle :
    </p>
    <br>
    <p>
        Un projet d’étude réalisé en été 1956 au College Dartmouth<sup id="note1"><a href="#footnote1" title="Note n°1">1</a></sup>,
        situé dans le New Hampshire aux États Unis, marqua
        la naissance de l’appellation « intelligence artificielle ». Ce terme a été initialement proposée par
        l’informaticien et cogniticien John McCarthy, à l’origine de ce colloque. Ce séminaire de recherche avait pour
        objectif de réunir onze scientifiques de renom pour ainsi évaluer l’hypothèse que :
    </p>
    <p class="text-center">
        «chaque aspect de l’apprentissage ou toute autre caractéristique de l’intelligence, peut être décrit assez
        précisément pour être simuler par ordinateur».<sup id="note2"><a href="#footnote2" title="Note n°2">2</a></sup>
    </p>


    <br>
    <a title="&quot;null0&quot;, CC BY-SA 2.0 &lt;https://creativecommons.org/licenses/by-sa/2.0&gt;, via Wikimedia Commons"
       href="https://commons.wikimedia.org/wiki/File:John_McCarthy_Stanford.jpg">
        <img class="rounded mx-auto d-block"
             width="256"
             alt="John McCarthy Stanford"
             src="{% static 'img/accueil/john_mccarthy.jpeg' %}"></a>
    <br>
    <p class="text-center ">John McCarthy en 2006, pionnier de l'intelligence artificielle.
        <br>
        <br>
    <p>
        Dans cette optique, deux approches ont été développées au fil des années :
    </p>
    <p>
        - celle dite déterministe, cette approche consiste en l’implémentation d’une succession d’états connus et
        maitrisés à l’avance, qui restera inchangée. Ainsi, un algorithme déterministe produira toujours la même sortie
        pour une même entrée.
    </p>
    <p>
        - celle qualifiée de probabiliste ou encore stochastique réalisant des prédictions en sortie d’une modélisation
        statistique bayésienne, à partir de données d’observations proposées en entrée. En opposition par rapport à
        l’approche déterministe, un algorithme probabiliste est non-déterministe, en d’autres termes, pour une même
        entrée il peut présenter des résultats différents.
    </p>
    <br>
    <p class="text-center fw-bold text-decoration-underline">
        Le machine learning :
    </p>
    <br>
    <p>
        Traduit en français par l’apprentissage automatique, le machine learning est un des nombreux champs d’étude de
        l’intelligence artificielle. Cette technique de programmation repose sur une approche probabilistique
        solutionnant un problème en apprenant à partir d’un ensemble de données. D'une manière singulière, la
        modélisation statistique n'a pas besoin d'être explicitement programmée pour apprendre d'un ensemble de données.
        L'expression machine learning a été utilisée pour la première fois en 1952 par Arthur Samuel, un chercheur en
        intelligence artificielle américain, pour qualifier son programme capable de jouer aux dames et d’apprendre au
        fur et à mesures des parties.<sup id="note3"><a href="#footnote3" title="Note n°3">3</a></sup>
    </p>
    <br>
    <a title="Xl2085, CC BY-SA 4.0 &lt;https://creativecommons.org/licenses/by-sa/4.0&gt;, via Wikimedia Commons"
       href="https://commons.wikimedia.org/wiki/File:This_is_the_photo_of_Arthur_Samuel.jpg">
        <img class="rounded mx-auto d-block"
             width="256"
             alt="This is the photo of Arthur Samuel"
             src="{% static 'img/accueil/arthur_samuel.jpeg' %}"></a>
    <br>
    <p class="text-center"> Arthur Samuel, pionnier américain du jeu sur ordinateur,
        <br>
        de l'intelligence artificielle et de l'apprentissage automatique.</p>
    <br>
    <br>
    <p class="text-center fw-bold text-decoration-underline">
        Les réseaux de neurones artificiels :
    </p>
    <br>
    <p>
        De l’anglais ANNs signifiant <span class="fst-italic">Artificial neural networks</span>, ces réseaux sont des
        implémentations originellement inspirées de réseaux de neurones biologiques. À posteriori, les ANNs ont été
        développés et optimisés à l’aide de méthodes d’apprentissages statistiques. Le premier réseau de neurone
        artificiel a été inventé en 1958 par le psychologue américain Franck Rosenblatt<sup id="note4"><a
            href="#footnote4" title="Note n°4">4</a></sup>, souvent considéré de nos jours comme le père du <span
            class="fst-italic">deep learning</span>.

    </p>
    <br>
    <a title="AnonymousUnknown author, CC BY-SA 4.0 &lt;https://creativecommons.org/licenses/by-sa/4.0&gt;, via Wikimedia Commons"
       href="https://commons.wikimedia.org/wiki/File:Rosenblatt_21.jpg">
        <img class="rounded mx-auto d-block"
             width="256"
             alt="Rosenblatt 21"
             src="{% static 'img/accueil/franck_rosenblatt.jpeg' %}"></a>
    <br>
    <p class="text-center">

        Franck Rosenblatt souvent considéré comme le père du <span class="fst-italic">deep learning</span>.
    </p>
    <br>
    <p class="text-center fw-bold text-decoration-underline">
        Le deep learning :
    </p>
    <br>
    <p>
        Ce procédé désigne l’utilisation d'une multitude de couches de neurones dans un réseau de neurones artificiels.
        Chaque couche de neurones prend en entrée la sortie de la précédente. En outre, cet agencement de couches en
        ajoutant de la profondeur au réseau, favorise la résolution de problèmes complexes. L’expression <span
            class="fst-italic">deep Learning</span> a été utilisée pour la première fois en 1986 par Rina Dechter<sup
            id="note5"><a href="#footnote5" title="Note n°5">5</a></sup>, une éminente professeure d’informatique à
        l’université de Californie, Irvine.
    </p>
    <br>
    <a title="Zichmich, CC BY-SA 3.0 &lt;https://creativecommons.org/licenses/by-sa/3.0&gt;, via Wikimedia Commons"
       href="https://commons.wikimedia.org/wiki/File:Rina_Dechter.jpg">
        <img class="rounded mx-auto d-block"
             width="256"
             alt="Rina Dechter"
             src="{% static 'img/accueil/rina_dechter.jpeg' %}"></a>
    <br>
    <p class="text-center">
        Rina Dechter, la première personne à utiliser l'expression <span class="fst-italic">deep Learning</span>.
    </p>
    <br>
    <p class="text-center fw-bold text-decoration-underline">
        Le réseau de neurones convolutifs :
    </p>
    <br>
    <p>
        Il s’agit d’un type de réseaux de neurones artificiels inspiré du cortex visuel d’animaux où le traitement
        d’images s’effectue en deux étapes. La première consiste à extraire des caractéristiques : un groupe de neurones
        analyse des petits blocs de pixels appelés champs récepteurs glissant le long de l’image. Cette méthode a pour
        but de reconnaître dans plusieurs zones de l’image des caractéristiques simples : des traits verticaux,
        horizontaux, obliques. Le modèle va dans la deuxième étape combiner les différents motifs reconnus précédemment,
        pour reconnaître des formes plus grandes et plus complexes comme les contours d’un objet,
        d’une personne.
    </p>
    <br>
    <p class="text-center fw-bold text-decoration-underline">
        Le réseau de neurones récurrents :
    </p>
    <br>
    <p>
        Un réseau de neurones récurrents est principalement destiné à la prédiction de séquences dans le domaine du
        traitement
        du langage naturel ainsi que la reconnaissance vocale. Ce type de réseau dispose pour chaque neurone, d’une
        technologie de mémorisation. Les informations enregistrées correspondent aux états ou aux prédictions traitées
        précédemment, afin d’être utilisées en entrée du réseau. Par conséquent, cet algorithme se renvoie le résultat à
        lui-même; ce procédé est en effet indispensable pour mémoriser et traiter des séquences de manière récurrente,
        pour ainsi réaliser des prédictions.
    </p>
    <br>
    <hr>
</div>
<div id="reference" style = "font-size:14px">
    <p class="text-decoration-underline">
        Références :
    </p>
    <p id="footnote1"><a href="#note1"><sup>1</sup></a>
        More, Trenchard, 1956,Dartmouth Conference on Artificial Intelligence Reports on the 5th and 6th Weeks.,<a
                href="http://raysolomonoff.com/dartmouth/boxa/dart56more5th6thweeks.pdf">
            http://raysolomonoff.com/dartmouth/boxa/dart56more5th6thweeks.pdf.</a>
    </p>
    <p id="footnote2"><a href="#note2"><sup>2</sup></a>
        McCarthy, J., Minsky, M., Rochester, N., Shannon, C.E., A Proposal for the Dartmouth Summer Research Project
        on Artificial Intelligence.,
        <a href="http://raysolomonoff.com/dartmouth/boxa/dart564props.pdf">
            http://raysolomonoff.com/dartmouth/boxa/dart564props.pdf, August, 1955.</a>
    </p>
    <p id="footnote3"><a href="#note3"><sup>3</sup></a>
        Arthur, Samuel (1959-03-03). "Some Studies in Machine Learning Using the Game of Checkers". IBM Journal of
        Research and Development.3 (3): 210–229.
    </p>
    <p id="footnote4"><a href="#note4"><sup>4</sup></a>
        Rosenblatt, Frank. "The perceptron: a probabilistic model for information storage and organization in the
        brain. "Psychological review 65.6 (1958): 386.
    </p>
    <p id="footnote5"><a href="#note5"><sup>5</sup></a>
        Dechter, Rina. "Learning while searching in constraint-satisfaction problems." (1986): 178-185.
    </p>
</div>

{% endblock content %}

siteweb/templates/site/contact.html
{% extends 'base.html' %}
{% load static %}


{% block title %} Contact {% endblock %}

{% block content %}


<div class="col-12">
    <br>
    <br>
    <div class="row justify-content-center">
        <div class="col-md-9 ">
            <form action="" method="post">
                {% csrf_token %}
                <!--  Mesure de sécurité créant un identifiant unique au formulaire -->
                <tr>
                    <th>
                        <label for="id_email">Email:</label>
                    </th>
                    <td>
                        <input type="email" name="from_email" maxlength="254" required id="id_email">
                    </td>
                </tr>
                <tr>
                    <th>
                        <label for="id_subject">Sujet :</label>
                    </th>
                    <td>
                        <input type="text" name="subject" maxlength="255" required id="id_subject">
                    </td>
                </tr>
                <tr>
                    <th>
                        <label for="id_message">Message :</label>
                    </th>
                    <td>
                        <textarea name="message" cols="40" rows="10" required id="id_message"></textarea>
                    </td>
                </tr>
                <script src='https://www.google.com/recaptcha/api.js'></script>

                <div class="col-md-12">
                    <div class="g-recaptcha" data-sitekey="6LcGUqseAAAAAGwMVcW52RQiG_cz3gjknHpXNc9g"></div>
                </div>
                <br>
                <input type="submit" value="Envoyer">
            </form>
        </div>
    </div>
</div>

{% endblock content %}